<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="m-bang-isharma1" name="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests" tests="47" failures="9" timestamp="14 Mar 2018 09:39:07 GMT" time="1176.030" errors="0">
  <testcase name="assetGroupNameTest" time="0.140" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueTimestampIsNotEmptyIn8H1WTabTest" time="0.000" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="switchTo1W8HTabTest" time="18.211" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="maxLabelIn1HTabTest" time="9.588" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="MAX label is not displayed, exception details are: java.lang.NullPointerException">
      <![CDATA[java.lang.AssertionError: MAX label is not displayed, exception details are: java.lang.NullPointerException
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.maxLabelIn1HTabTest(FCCM3560SessionDetailPageTests.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- maxLabelIn1HTabTest -->
  <testcase name="measurementValueTimestampIsNotEmptyIn1W3WTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueIn1W8HTabTest" time="2.567" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="Live value is coming as stale for sensor 1, exception details are: java.lang.StringIndexOutOfBoundsException: String index out of range: -1">
      <![CDATA[java.lang.AssertionError: Live value is coming as stale for sensor 1, exception details are: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.measurementValueIn1W8HTabTest(FCCM3560SessionDetailPageTests.java:776)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- measurementValueIn1W8HTabTest -->
  <testcase name="gateWayNameTest" time="0.116" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="switchTo1H8HTabTest" time="16.552" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="unitInMeasurementValueIn8H1HTabTest" time="0.000" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="Unit is not accurate 1, exception details are: java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Unit is not accurate 1, exception details are: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.unitInMeasurementValueIn8H1HTabTest(FCCM3560SessionDetailPageTests.java:865)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- unitInMeasurementValueIn8H1HTabTest -->
  <testcase name="measurementValueIn8H1HTabTest" time="2.339" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="Live value is coming as stale for sensor 1, exception details are: java.lang.StringIndexOutOfBoundsException: String index out of range: -1">
      <![CDATA[java.lang.AssertionError: Live value is coming as stale for sensor 1, exception details are: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.measurementValueIn8H1HTabTest(FCCM3560SessionDetailPageTests.java:849)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- measurementValueIn8H1HTabTest -->
  <testcase name="measurementValueTimestampIsNotEmptyIn1HTabTest" time="0.000" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="assetCountTextVisibleTest" time="0.116" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="sensorsStaticTextVisibleTest" time="0.140" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="switchTo3W1WTabTest" time="18.019" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="assetNameTest" time="0.147" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="sessionStartUserNameTest" time="0.141" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="vibrationUnitTest" time="0.478" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueIn1H8HTabTest" time="1.939" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="unitInMeasurementValueIn1HTabTest" time="0.000" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="Unit is not accurate 1, exception details are: java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Unit is not accurate 1, exception details are: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.unitInMeasurementValueIn1HTabTest(FCCM3560SessionDetailPageTests.java:427)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- unitInMeasurementValueIn1HTabTest -->
  <testcase name="yAxisLabelIn1HTabTest" time="0.101" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueTimestampIsNotEmptyIn1H8HTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="startTimeStaticTextVisibleTest" time="0.138" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="unitInMeasurementValueIn1W3WTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="graphDisplayedTest" time="0.232" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueIn8H1WTabTest" time="1.760" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="switchTo1W3WTabTest" time="17.400" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="machineLearningMessageTest" time="0.148" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="switchTo8H1HTabTest" time="17.748" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueIn3W1WTabTest" time="1.985" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueIn1HTabTest" time="2.403" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="Live value is coming as stale or too high for sensor 1, exception details are: java.lang.StringIndexOutOfBoundsException: String index out of range: -1">
      <![CDATA[java.lang.AssertionError: Live value is coming as stale or too high for sensor 1, exception details are: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.measurementValueIn1HTabTest(FCCM3560SessionDetailPageTests.java:411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- measurementValueIn1HTabTest -->
  <testcase name="unitInMeasurementValueIn1W8HTabTest" time="0.000" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="Unit is not accurate 1, exception details are: java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Unit is not accurate 1, exception details are: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.unitInMeasurementValueIn1W8HTabTest(FCCM3560SessionDetailPageTests.java:792)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- unitInMeasurementValueIn1W8HTabTest -->
  <testcase name="xAxisLabelIn1HTabTest" time="12.395" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueTimestampIsNotEmptyIn1W8HTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="sessionStartTimeTest" time="0.146" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="livePollingTest" time="1028.669" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="No live polling is happening on sensor 0, exception details are: java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No live polling is happening on sensor 0, exception details are: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.livePollingTest(FCCM3560SessionDetailPageTests.java:898)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- livePollingTest -->
  <testcase name="sensorCountAndTypeTest" time="0.155" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="zAxisLabelIn1HTabTest" time="0.109" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueIn1W3WTabTest" time="1.516" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueTimestampIsNotEmptyIn3W1WTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="unitInMeasurementValueIn3W1WTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="unitInMeasurementValueIn1H8HTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="unitInMeasurementValueIn8H1WTabTest" time="0.001" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="testPointNameTest" time="0.145" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="measurementValueTimestampIsNotEmptyIn8H1HTabTest" time="0.000" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="switchTo8H1WTabTest" time="17.050" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="sessionTileStatusTest" time="2.175" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests"/>
  <testcase name="minLabelIn1HTabTest" time="1.254" classname="com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests">
    <failure type="java.lang.AssertionError" message="MIN label is not displayed, exception details are: java.lang.NullPointerException">
      <![CDATA[java.lang.AssertionError: MIN label is not displayed, exception details are: java.lang.NullPointerException
	at org.testng.Assert.fail(Assert.java:94)
	at com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests.minLabelIn1HTabTest(FCCM3560SessionDetailPageTests.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- minLabelIn1HTabTest -->
</testsuite> <!-- com.connect.fluke.app.tests.FCCM3560SessionDetailPageTests -->
